### ISSUE TITLE
Demo App is down

### ISSUE THREAD

**Issue by stevepiercy** [niteoweb/pyramid-realworld-example-app#127]
https://pyramid-realworld.herokuapp.com/

## Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command

```
heroku logs --tail
```

**Comment by sayanarijit** [comment]
@stevepiercy thanks for reporting this.

@zupo I see it has autoidle installed for the main app instead of the review apps. Is it intentional?

<img width="374" alt="image" src="https://user-images.githubusercontent.com/11632726/96356840-a7aa3c80-1111-11eb-8a6a-67ba0795aea1.png">

**Comment by zupo** [comment]
Hey Steve! I'm testing a new Heroku plugin that auto-shuts-down apps when there is no use. This will save %80+ of costs we have with the demo app. 

The drawback is, that the first request will error. The second request will be slow (while the app is starting), and from the third request onwards, things are normal. 

There is a way to work-around the first request erroring, but we need to either:
* serve the app on `*.autoidle.com` instead of `*.herokuapp.com`, which is not great for people used to Heroku (as they autoidle plugin is a new thing and not mainstream yet) 
* serve the app on a custom domain, such as `pyramid-realworld.niteo.co` which I am not a fan of because of using Niteo's domain. Just realized, can I server this demo app on something like `realworld.trypyramid.com`?

**Comment by stevepiercy** [comment]
It might be possible to run it on our existing Linode. We host https://deformdemo.pylonsproject.org/ there. It costs USD$5 per month for the Linode and another USD$2 for backups and includes DNS, but we get credits donated to us by Linode.

Either `realworld.trypyramid.com` or `realworld.pylonsproject.org` would work, but I would go with the latter as `trypyramid.com` is exclusively a Pyramid marketing website (a static Hugo site hosted with GitHub pages).

We have a sikrit repo that uses Ansible for deployment of stuff to Linode, including setting up Let's Encrypt certificates. I can grant @zupo access or anyone else willing to do the work. I can also help with orientation. Please let me know, and I can make it happen.

**Comment by zupo** [comment]
I'm -1 on running this on Linode. Heroku has auto-deployment on every change on master, and it creates a staging app for every PR that is created, so changes can be checked on an actual running app. I don't want to spend time with Ansible to get this to work on Linode. 

I don't understand why it matters that `trypyramid.com` is running on Hugo? It should be a purely "marketing" decision what domain to use, as Heroku only needs one CNAME record in the DNS settings, nothing needs to be configured on any server. And since this is a Pyramid realdworld example, I thought it's more appropriate to be on a `trypyramid.com` subdomain.

**Comment by stevepiercy** [comment]
Perhaps I misunderstood what you want. I thought you wanted hosting. Are you saying you do **not** want hosting, but only a DNS A/AAAA record to point to a specific IP address or a CNAME?

I really don't want to expand the use of `trypyramid.com` beyond its sole purpose as a marketing website. `*.pylonsproject.org` is more appropriate. Perhaps one of these would be better?

- pyramid-openapi3.pylonsproject.org
- pyramid-openapi3-demo.pylonsproject.org
- pyramid-openapi3-realworld.pylonsproject.org
- pyramid-openapi3-realworld-demo.pylonsproject.org

**Comment by zupo** [comment]
Yeah, I do not want hosting, only DNS CNAME record. `pyramid-openapi3.pylonsproject.org` is good. Please point CNAME to `ssl.autoidleapp.com`.

**Comment by stevepiercy** [comment]
Done!

**Comment by zupo** [comment]
Sweet, thanks!

**Comment by zupo** [comment]
The Swagger Explorer is broken:

<img width="832" alt="Screenshot 2020-10-19 at 10 02 53" src="https://user-images.githubusercontent.com/311580/96424195-43ab7500-11f2-11eb-9062-75ab7a3e461f.png">

**Comment by stevepiercy** [comment]
Here's the CNAME record.

![Screen Shot 2020-10-19 at 2 06 11 AM](https://user-images.githubusercontent.com/102112/96424576-be9f6c00-11af-11eb-9354-08f9228b7a09.png)

And it works for me.

https://pyramid-openapi3.pylonsproject.org/

![Screen Shot 2020-10-19 at 2 07 41 AM](https://user-images.githubusercontent.com/102112/96424688-e42c7580-11af-11eb-91a4-a85f3d54c953.png)

**Comment by stevepiercy** [comment]
Oh, maybe that's just the app, and you want the explorer?

**Comment by zupo** [comment]
The app works, the API explorer (at `/api`) does not.

**Comment by zupo** [comment]
Figured out what's going on (thanks @dz0ny for the help!)::
1. AutoIdle acts as a proxy to `*.herokuapp.com`.
2. `pyramid_openapi3` users `route_url` to construct the `spec_url`, which takes the HOSTNAME
3. Since the request is a simple TCP proxy to `*.herokuapp.com`, the HOSTNAME is `pyramid-realworld.herokuapp.com` and hence the `spec_url` is https://pyramid-realworld.herokuapp.com/openapi.yaml. 

Possible solution:
Instead of `route_url`, use `route_path` and then in `index.html` of explorer prepend `spec_url` (which will now be just a relative `/openapi.yaml` with `document.location.origin` (hostname taken from the browser).

**Comment by domenkozar** [comment]
There's probably a way to tell heroku what the right HOST is? Usually with `X-Forwarded-Host` or something similar.

In general it's best that heroku knows the correct hostname it's serving under.

**Comment by zupo** [comment]
It's actually Pyramid that needs to be aware of it, not Heroku. Something like this can be a solution as well? https://github.com/Pylons/pyramid/issues/1435

**Comment by zupo** [comment]
Or extend https://github.com/niteoweb/pyramid_heroku/blob/master/pyramid_heroku/client_addr.py with support for `x-forwarded-host` besides `x-forwarded-for`.

**Comment by domenkozar** [comment]
That would work if heroku sets x-forwarded-host correct (which it hopefully should).

**Comment by zupo** [comment]
As per https://devcenter.heroku.com/articles/http-routing#heroku-headers, `X-Forwarded-Host` is not trusted for security reasons.

**Comment by domenkozar** [comment]
That's probably referring to headers passed to heroku being filtered out. It would help to have all headers that heroku passes to the application, I'd suspect in there there's a way to extract the correct hostname. But I have zero knowledge about autoidle proxy so I could be wrong :)

**Comment by zupo** [comment]
@sgasser (author of AutoIdle) suggests using `X-Forwarded-Host`. Lemme see if it gets through Heroku's load balancer (even though they say this header "is not trusted").

**Comment by zupo** [comment]
This is how Pyramid sees a request proxied by AutoIdle:

```
{
    'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f04f5c95940>,
    'wsgi.version': (1, 0),
    'wsgi.multithread': False,
    'wsgi.multiprocess': True,
    'wsgi.run_once': False,
    'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
    'wsgi.input_terminated': True,
    'SERVER_SOFTWARE': 'gunicorn/20.0.4',
    'wsgi.input': <_io.BytesIO object at 0x7f04f5bac720>,
    'gunicorn.socket': <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.19.92.166', 45843), raddr=('10.159.227.245', 32690)>,
    'REQUEST_METHOD': 'GET',
    'QUERY_STRING': 'limit=10&offset=0',
    'RAW_URI': '/api/articles?limit=10&offset=0',
    'SERVER_PROTOCOL': 'HTTP/1.1',
    'HTTP_HOST': 'pyramid-realworld.herokuapp.com',
    'HTTP_CONNECTION': 'close',
    'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36',
    'HTTP_ACCEPT': '*/*',
    'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9,sl;q=0.8,si;q=0.7',
    'HTTP_COOKIE': '_ga=GA1.2.257283249.1603101769; _gid=GA1.2.1833084198.1603101769',
    'HTTP_REFERER': 'https://pyramid-openapi3.pylonsproject.org/',
    'HTTP_SEC_FETCH_DEST': 'empty',
    'HTTP_SEC_FETCH_MODE': 'cors',
    'HTTP_SEC_FETCH_SITE': 'same-origin',
    'HTTP_X_FORWARDED_FOR': '3.125.76.144',
    'HTTP_X_FORWARDED_HOST': 'pyramid-openapi3.pylonsproject.org',
    'HTTP_X_FORWARDED_PROTO': 'https',
    'HTTP_X_REQUEST_ID': '3b725d84-0b14-45c9-a7f1-433f4c6078fe',
    'HTTP_X_FORWARDED_PORT': '443',
    'HTTP_VIA': '1.1 vegur',
    'HTTP_CONNECT_TIME': '4',
    'HTTP_X_REQUEST_START': '1603104811887',
    'HTTP_TOTAL_ROUTE_TIME': '0',
    'wsgi.url_scheme': 'https',
    'REMOTE_ADDR': '10.159.227.245',
    'REMOTE_PORT': '32690',
    'SERVER_NAME': '0.0.0.0',
    'SERVER_PORT': '45843',
    'PATH_INFO': '/api/articles',
    'SCRIPT_NAME': '',
    'CONTENT_LENGTH': '0',
    'webob.is_body_seekable': True,
    'retry.attempt': 0,
    'retry.attempts': 3,
    'tm.active': True,
    'tm.manager': <transaction._manager.ThreadTransactionManager object at 0x7f04f931cf40>,
    'pyramid_openapi3.validate_response': True,
    'pyramid_openapi3.validate_request': True,
    'webob._parsed_query_vars': (GET([('limit',
    '10'), ('offset',
    '0')]),
    'limit=10&offset=0'),
}
```

Sure enough, `HTTP_X_FORWARDED_HOST` is there. I'll add support for `HTTP_X_FORWARDED_HOST`  to https://github.com/niteoweb/pyramid_heroku.

**Comment by domenkozar** [comment]
Note that heroku router doesn't respect those headers since they might come from the user making the HTTP request.

But trusting those from AutoIdle should be safe - something to consider for pyramid_heroku. Ideally heroku would filter out all those headers so that only proxies inside heroku can set those, but I haven't verified that.

**Comment by zupo** [comment]
It works!

<img width="994" alt="Screenshot 2020-10-19 at 13 42 31" src="https://user-images.githubusercontent.com/311580/96452462-f4c10800-1210-11eb-8fa1-d7f4b88f6672.png">
