### ISSUE TITLE
Consider using view classes

### ISSUE THREAD

**Issue by cguardia** [niteoweb/pyramid-realworld-example-app#32]
In article views you use the same code several times:

https://github.com/niteoweb/pyramid-realworld-example-app/blob/987e6feb50fd459d1c9f148b0601b9d23ffd49d2/src/conduit/article/views.py#L130

Using a view class here instead of separate methods would allow you to set the article in the view __init__ method. That way, the code is leaner, plus you can also use the @view_defaults decorator to set the api and renderer parameters as defaults.

**Comment by zupo** [comment]
Good point, I'll prepare a PR or two to see how it works.

**Comment by zupo** [comment]
I don't usually use view classes so I might be missing things, but it seems to me that they will just complicate code. Let me elaborate:

To remove the `article = object_or_404( ` duplication I'd create a view class that sets `self.article` in `def __init__()`. Then I can put the `article`, `update`, `delete`, `favorite` and `unfavorite` functions into this class. But I have to leave `create`, `paginate`, `feed` and `articles` outside of the view class. Then one might wonder why some views are in a class and some are individual views. Also, grouping of CRUD-related functions together in the file cannot be done, since `create` function needs to stay out of the view class. Tests will likely require more elaborate setup code too.

Other view modules seem to gain even less from moving them to view classes. And I'm reluctant to introduce a new approach that someone new to Pyramid should learn to understand this code, for only a marginal removal of duplication. 

What am I missing?

**Comment by cguardia** [comment]
Usually, you wouldn't need to leave anything out. The value of self.article could just be None for the other views, and default parameters can be overridden in the individual views. However, the use of the 404 pattern here makes this impossible, so I have to agree that this limits the benefits. Sorry I didn't look into it more closely before posting.

**Comment by zupo** [comment]
Thanks!

**Comment by enkidulan** [comment]
Oh no, don't close this issue. Maybe the proposed solution was not the best fit, but the problem of code duplication remains... Another thing that I noticed is that there is a mix of entities in articles. I'll try to explain. 

> Then I can put the article, update, delete, favorite and unfavorite functions into this class. But I have to leave create, paginate, feed and articles outside of the view class.

`favorite and unfavorite` and `put the article, update, delete` actually perform operations on different entities, so it would be a mistake to put them together. Same goes for a `feed` - it is a separate entity. `paginate` is not an entity at all, it is a general function-helper, so it does not make sense even to consider it.

Following endpoints grouping would make sense:
* article put, update, delete, create, articles
* article favorite and unfavorite 
* feed

So the first obvious solution for having REST endpoints grouping right and without code duplication is to use a REST framework on top of Pyramid. But in that case, the app would be more about used REST-framework and less about Pyramid.

The other solution I can think of is to move separate entities into different modules and use factories, so the code would look somewhat like this:

```
...
config.add_route("article", "/api/articles/{slug}", factory=article_factory)
config.add_route("article.favorite", "/api/articles/{slug}/favorite", factory=article_factory)

...

def article_factory(request):
    return object_or_404(
        Article.by_slug(
            request.openapi_validated.parameters["path"]["slug"], db=request.db
        )
    )

...

@view_config(route_name="article", renderer="json", request_method="DELETE", openapi=True)
def delete(request: Request, , context: Article) -> None:
    """Delete an article."""
    request.db.delete(context)
    return None


@view_config(route_name="article.favorite", renderer="json", request_method="POST", openapi=True)
def favorite(request: Request, context: Article) -> SingleArticleResponse:
    """Favorite an article."""
    request.user.favorite(context)
    return {"article": }

```
And since factories are a part of [pyramid beginner tutorial](https://docs.pylonsproject.org/projects/pyramid/en/latest/tutorials/wiki2/authorization.html) that should not be a confusing 'new approach that someone new to Pyramid should learn'.

I have a feeling that I'm adressing two issues here, probably will create a separate one for mixed entities endpoints.
