### ISSUE TITLE
Consider cookiecutter template rather than github's builtin `generate`

### ISSUE THREAD

**Issue by mandarvaze** [niteoweb/pyramid-realworld-example-app#57]
1. Cookiecutter will allow atleast *some* customization via interactive mode (questions) during the project creation phase. Otherwise, the user needs to start a whole lot of customization before they can start "using" the repo.
2. It is also not tied to github (User need not have github account, can use other VCS options)

**Comment by zupo** [comment]
I have a long history of providing templates for projects:
* 
* 
* 
* 
* 

And all of them got outdated almost the day after I released them. This repo is an exception. Why is that? Because it is not a template, but a runnable project. It's very easy for me to add a new best practice or pattern into it, because I can test and run it quickly. If I'd had to work on the code indirectly, via templates, I'd never do it. And then it would get outdated. 

So, as an experiment, I want to keep this repo "not-a-template".

**Comment by mandarvaze** [comment]
I agree that keeping a template up to date is gonna take a lot of time.
But I wanna give it a try.
So I've created this : https://github.com/mandarvaze/cookiecutter-pyramid-realworld

If nothing, it was a good way to learn about cookiecutter.
